#!/usr/bin/env bash
#
# Regenerates the "Code Statistics" block in README.md.
#
# Runs cloc per module for file/line counts, parses JUnit XML for Kotlin test
# counts, and parses Jest's --json output for backend test counts. Splices the
# resulting markdown table between the <!-- stats-start --> and <!-- stats-end -->
# markers in README.md.
#
# Safe to run locally:
#   sudo apt-get install -y cloc jq
#   ./gradlew test
#   npm --prefix backend test -- --json --outputFile=/tmp/jest.json
#   ./scripts/update-readme-stats.sh
#
# Environment variables:
#   JEST_JSON   Path to Jest --json output. Default: /tmp/jest.json
#   README      Path to README.md. Default: <repo-root>/README.md

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

README="${README:-$REPO_ROOT/README.md}"
JEST_JSON="${JEST_JSON:-/tmp/jest.json}"
MODULES=(app-phone app-tv core backend)

for cmd in cloc python3; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "error: required command '$cmd' not found in PATH" >&2
    exit 1
  fi
done

# cloc excludes build artefacts; Gradle "build/" and npm "node_modules/" would
# otherwise inflate counts with generated or vendored code. Language allowlist
# keeps JSON lockfiles (package-lock.json, ~4 kLOC) and ProGuard configs out of
# the counts so the table reflects authored source, not vendored manifests.
CLOC_EXCLUDES="build,.gradle,node_modules,coverage,out"
CLOC_LANGS="Kotlin,Java,JavaScript,TypeScript,XML,Gradle"

# Emit "<files>\t<loc>" for a directory, summed across the counted languages.
cloc_module() {
  local dir="$1"
  if [[ ! -d "$dir" ]]; then
    echo "0	0"
    return
  fi
  cloc --json --quiet \
    --exclude-dir="$CLOC_EXCLUDES" \
    --include-lang="$CLOC_LANGS" \
    "$dir" 2>/dev/null \
    | python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    print("0\t0"); sys.exit(0)
summary = data.get("SUM", {})
print(f"{summary.get('"'"'nFiles'"'"', 0)}\t{summary.get('"'"'code'"'"', 0)}")
'
}

# Sum JUnit XML counts under <module>/**/build/test-results/testDebugUnitTest/*.xml.
# The Android Gradle Plugin writes unit-test results per build variant
# (testDebugUnitTest / testReleaseUnitTest); matching only the debug variant
# avoids double-counting when `./gradlew test` runs both.
# Output: "<tests>\t<failures>\t<errors>\t<skipped>"
junit_counts() {
  local module="$1"
  python3 - "$module" <<'PY'
import glob, os, sys, xml.etree.ElementTree as ET

module = sys.argv[1]
total = failures = errors = skipped = 0
pattern = os.path.join(module, "**", "build", "test-results", "testDebugUnitTest", "*.xml")
for path in glob.glob(pattern, recursive=True):
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError:
        continue
    # Gradle writes one <testsuite> per class; sum attributes.
    total += int(root.get("tests", 0))
    failures += int(root.get("failures", 0))
    errors += int(root.get("errors", 0))
    skipped += int(root.get("skipped", 0))
print(f"{total}\t{failures}\t{errors}\t{skipped}")
PY
}

# Read Jest summary if available. Output: "<tests>\t<failures>\t<errors>\t<skipped>"
jest_counts() {
  if [[ ! -f "$JEST_JSON" ]]; then
    echo "0	0	0	0"
    return
  fi
  python3 - "$JEST_JSON" <<'PY'
import json, sys
try:
    with open(sys.argv[1]) as f:
        data = json.load(f)
except Exception:
    print("0\t0\t0\t0"); sys.exit(0)
total = data.get("numTotalTests", 0)
failures = data.get("numFailedTests", 0)
skipped = data.get("numPendingTests", 0) + data.get("numTodoTests", 0)
# Jest lumps errors into failures; keep the errors column at 0.
print(f"{total}\t{failures}\t0\t{skipped}")
PY
}

format_tests() {
  local total="$1" failures="$2" errors="$3" skipped="$4"
  if [[ "$total" -eq 0 ]]; then
    echo "—"
    return
  fi
  local bad=$((failures + errors))
  local passed=$((total - bad - skipped))
  if [[ "$bad" -gt 0 ]]; then
    echo "${passed}/${total} (${bad} failing)"
  elif [[ "$skipped" -gt 0 ]]; then
    echo "${passed}/${total} (${skipped} skipped)"
  else
    echo "${total}"
  fi
}

format_int() {
  # Thin-space thousand separators so wide numbers stay readable in the table
  # (e.g. 13 607 rather than 13607). Python's format spec is locale-independent.
  python3 -c "print(f\"{int(${1}):,}\".replace(',', '\u2009'))"
}

TMP_BLOCK="$(mktemp)"
trap 'rm -f "$TMP_BLOCK"' EXIT

{
  echo "_Last updated: $(date -u +'%Y-%m-%d') — generated by [\`scripts/update-readme-stats.sh\`](scripts/update-readme-stats.sh)._"
  echo
  echo "| Module | Files | Lines of code | Tests |"
  echo "|---|---:|---:|---:|"

  total_files=0
  total_loc=0
  total_tests=0
  total_bad=0
  total_skipped=0

  for module in "${MODULES[@]}"; do
    IFS=$'\t' read -r files loc < <(cloc_module "$module")
    if [[ "$module" == "backend" ]]; then
      IFS=$'\t' read -r tests failures errors skipped < <(jest_counts)
    else
      IFS=$'\t' read -r tests failures errors skipped < <(junit_counts "$module")
    fi

    total_files=$((total_files + files))
    total_loc=$((total_loc + loc))
    total_tests=$((total_tests + tests))
    total_bad=$((total_bad + failures + errors))
    total_skipped=$((total_skipped + skipped))

    printf "| \`%s\` | %s | %s | %s |\n" \
      "$module" \
      "$(format_int "$files")" \
      "$(format_int "$loc")" \
      "$(format_tests "$tests" "$failures" "$errors" "$skipped")"
  done

  printf "| **Total** | **%s** | **%s** | **%s** |\n" \
    "$(format_int "$total_files")" \
    "$(format_int "$total_loc")" \
    "$(format_tests "$total_tests" "$total_bad" 0 "$total_skipped")"
} > "$TMP_BLOCK"

# Splice the new block between the markers, preserving surrounding content.
python3 - "$README" "$TMP_BLOCK" <<'PY'
import sys, pathlib, re

readme_path = pathlib.Path(sys.argv[1])
block = pathlib.Path(sys.argv[2]).read_text()

text = readme_path.read_text()
pattern = re.compile(
    r"(<!-- stats-start -->)(.*?)(<!-- stats-end -->)",
    re.DOTALL,
)
if not pattern.search(text):
    sys.exit(
        "error: README is missing the <!-- stats-start --> / <!-- stats-end --> "
        "markers; add them manually first"
    )

new_text = pattern.sub(
    lambda _: f"<!-- stats-start -->\n{block}\n<!-- stats-end -->",
    text,
    count=1,
)
if new_text != text:
    readme_path.write_text(new_text)
    print(f"updated {readme_path}")
else:
    print(f"no change to {readme_path}")
PY
